### PR TITLE
mpin_user failing to build on ARM

### PR DESCRIPTION
**Pull request by gdamore**
Apparently having two calls to copy_from_user in ioctl causes us to blow past some limit on the amount of inlined code for this platform in some circumstances.

### CODE REVIEW

**Comment by gdamore** [comment]
Note that without this fix, we are completely stopped for ARM.
I'll be making a PR for wekapp to use this.

It does add one more pointer dereference to the code path, so very slightly less efficient, but it keeps the code a bit tighter by fitting it all in memory, so 🤷

**Review by ljmf00-wekaio — APPROVED** [review]
This looks good. I'm pretty sure we shouldn't enforce `-Winline` nor `-Werror` on user-compilable kernel modules. We don't control kernel headers and those can change in variety of ways.

**Review by BaruchWeka — APPROVED** [review]
This isn't performance-oriented code that should require this kind of treatment IMO.

**Comment by boaz-at-weka** [comment]
> Apparently having two calls to copy_from_user in ioctl causes us to blow past some limit on the amount of inlined code for this platform in some circumstances.

Its not the two calls, its the calling through a pointer that made gcc not inline the call to mpin_user_pin/unpin_page.
.
Anyway this is the wrong fix. See next comment

**Review by boaz-at-weka — CHANGES_REQUESTED** [review]
This is the wrong fix.
The correct fix is:
~~~
diff --git a/Makefile b/Makefile
index 6218209..ad4d313 100644
--- a/Makefile
+++ b/Makefile
@@ -12,6 +12,7 @@ PWD := $(shell pwd)
 
 # ~~~ This Part is the Kbuild side
 EXTRA_CFLAGS = -Winline -Wall -Werror -I$(PWD) -D MPIN_USER_VERSION=\"$(MPIN_USER_VERSION)\"
+EXTRA_CFLAGS += -Wno-error=inline
 obj-m := mpin_user.o
 
 # ~~~ This part is so we can use make inside the source dir to make below target options
~~~

**Comment by gdamore** [comment]
I fundamentally disagree with the answer ... it will *still* generate warnings, they just won't be treated as errors.

By using a single call to copy-from, the amount of code generated will be smaller, and be under whatever ridiculous threshold exists for inlining content.  Avoiding the warning altogether.

Now I don't understand why we are using -Werror and -Winline in the first place.  These seem like unfortunate flags to have when code has to be compiled in user environments that we don't control, as they likely increase brittleness like we have seen here.

**Comment by gdamore** [comment]
For the record, also, it is the two calls.  I did a trial before coming up with this version, where I reduced to two calls but didn't use a function pointer (I just unconditionally did a copy in first, which is wrong for the code architecturally, but allowed me to test the code.)

Also, if you'll look, you'll see that the copy code is not what is called by a function pointer.  The copyin happens normally, and I believe the code is probably still inlined, although honestly I'm perfectly fine if it is not -- there is no particular reason this code needs to be inlined here -- it's not performance critical as @BaruchWeka has indicated.

**Comment by gdamore** [comment]
The change to WEKAPP to use this commit merged last night already.  I'm moving ahead with merging this so that the tip of the branch reflects what we are using in the latest WEKAPP dev work.  If @boaz-at-weka wants to change this, a follow up set of PRs to make whatever changes are deemed appropriate can be made.

**Pull request merged**
